### ISSUE TITLE
Volume reset 100% each time.

### ISSUE THREAD

**Issue by The-Tasty-Jaffa** [Frederikam/FredBoat-Web#1]
Volume reset 100% each time.

**Comment by freyacodes** [comment]
Are you sure? This shouldn't happen unless the bot shard for some reason crashes or gets shut down improperly, which is something I intend to make fully persistent.

Btw, this is the repo for the (WIP) web dashboard for the bot. The correct repo is https://github.com/Frederikam/FredBoat

**Comment by The-Tasty-Jaffa** [comment]
Yes I'm sure it does that. - Crashes Relatively frequently then? (Ok shall I go and make this closed and reopen it on that repo?)

**Comment by freyacodes** [comment]
Please do, but the issue is rather that the volume isn't persistent. I think I might have some trouble with reloading once the bot restarts (which is rather frequently), causing it to not load songs and volume.
